openapi: "3.0.3"
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple food api
paths:
  /api/foods:
    get:
      tags:
        - FoodService
      summary: List all foods
      operationId: getFoods
      responses:
        '200':
          description: all food
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/FoodModel'

  /api/orders:
    get:
      tags:
        - OrderService
      summary: List orders of authenticated customer
      operationId: getOrders
      responses:
        '200':
          description: all order of authenticated customer
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/OrderModel'
    post:
      tags:
        - OrderService
      summary: Create order from the cart of body
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartModel'
      responses:
        '201':
          description: the created order from cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderModel'
        '400':
          description: Cart is empty or customer doesn't have enough balance

  /api/orders/{orderId}:
    get:
      tags:
        - OrderService
      summary: Get order of authenticated customer by orderId
      description: Returns a single Order
      operationId: getOrder
      parameters:
        - name: "orderId"
          in: "path"
          description: "Id of order to return"
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderModel'
        '403':
          description: Order is not owned by the authenticated customer
        '404':
          description: Order not found

components:
  schemas:
    FoodModel:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        calorie:
          type: number
        description:
          type: string
        price:
          type: number

    OrderItemModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        foodModel:
          $ref: '#/components/schemas/FoodModel'
        pieces:
          type: integer
        price:
          type: number

    OrderModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        price:
          type: number
        timestampCreated:
          type: string
        orderItemModels:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemModel'

    CartModel:
      type: object
      properties:
        orderItemModels:
          type: array
          default: [ ]
          items:
            $ref: '#/components/schemas/OrderItemModel'
        price:
          type: number
          default: 0
