/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.epam.training.food.api;

import com.epam.training.food.model.CartModel;
import com.epam.training.food.model.OrderModel;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-09-20T16:29:12.622199800+05:30[Asia/Calcutta]")
@Validated
@Tag(name = "OrderService", description = "the OrderService API")
public interface OrderServiceApi {

    /**
     * POST /api/orders : Create order from the cart of body
     *
     * @param cartModel  (required)
     * @return the created order from cart (status code 201)
     *         or Cart is empty or customer doesn&#39;t have enough balance (status code 400)
     */
    @Operation(
        operationId = "createOrder",
        summary = "Create order from the cart of body",
        tags = { "OrderService" },
        responses = {
            @ApiResponse(responseCode = "201", description = "the created order from cart", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrderModel.class))
            }),
            @ApiResponse(responseCode = "400", description = "Cart is empty or customer doesn't have enough balance")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/orders",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<OrderModel> createOrder(
        @Parameter(name = "CartModel", description = "", required = true) @Valid @RequestBody CartModel cartModel
    );


    /**
     * GET /api/orders/{orderId} : Get order of authenticated customer by orderId
     * Returns a single Order
     *
     * @param orderId Id of order to return (required)
     * @return search results matching criteria (status code 200)
     *         or Order is not owned by the authenticated customer (status code 403)
     *         or Order not found (status code 404)
     */
    @Operation(
        operationId = "getOrder",
        summary = "Get order of authenticated customer by orderId",
        description = "Returns a single Order",
        tags = { "OrderService" },
        responses = {
            @ApiResponse(responseCode = "200", description = "search results matching criteria", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrderModel.class))
            }),
            @ApiResponse(responseCode = "403", description = "Order is not owned by the authenticated customer"),
            @ApiResponse(responseCode = "404", description = "Order not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/orders/{orderId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<OrderModel> getOrder(
        @Parameter(name = "orderId", description = "Id of order to return", required = true, in = ParameterIn.PATH) @PathVariable("orderId") Long orderId
    );


    /**
     * GET /api/orders : List orders of authenticated customer
     *
     * @return all order of authenticated customer (status code 200)
     */
    @Operation(
        operationId = "getOrders",
        summary = "List orders of authenticated customer",
        tags = { "OrderService" },
        responses = {
            @ApiResponse(responseCode = "200", description = "all order of authenticated customer", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = OrderModel.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/orders",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<OrderModel>> getOrders(
        
    );

}
